# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app\\main_app.py',
     'app\\language_service.py',
     'app\\resp.py',
     'app\\translate_service.py',
     'app\\doc_service.py',
     'app\\__init__.py',
     'app\\model.py',
     'core\\enums.py',
     'core\\file.py',
     'core\\compare.py',
     'core\\doc_reader.py',
     'core\\xlsx_reader.py',
     'core\\__init__.py',
     'py_api.py',
     'alchemy\\enums\\__init__.py',
     'alchemy\\enums\\dialects.py',
     'alchemy\\__init__.py',
     'alchemy\\base_model.py',
     'alchemy\\db20.py',
     'alchemy\\helper.py',
     ],
    pathex=["D:\\aws\\eclinical40_auto_testing\\edktranslation\\src\\edktranslation"],
    binaries=[],
    datas=[('static\\view\\','static\\view'),
           ('static\\view\\assets\\*.js','static\\assets'),
           ('static\\view\\favicon.ico','static\\view'),
           ('static\\view\\src\\assets\\bootstrap\\js\\*.js','static\\view\\src\\assets\\bootstrap\\js'),
           ('static\\view\\src\\assets\\bootstrap\\css\\*.css','static\\view\\src\\assets\\bootstrap\\css'),
           ('static\\view\\src\\assets\\tabler\\js\\*.js','static\\view\\src\\assets\\tabler\\js'),
           ('static\\view\\src\\assets\\tabler\\css\\*.css','static\\view\\src\\assets\\tabler\\css'),
           ('static\\view\\src\\assets\\extensions\\*.js','static\\view\\src\\assets\\extensions'),
           ('static\\view\\src\\assets\\*.css','static\\view\\src\\assets'),
           ('static\\view\\src\\assets\\*.png','static\\view\\src\\assets'),
           ('static\\view\\src\\assets\\*.svg','static\\view\\src\\assets')],
    hiddenimports=['clr', 'System', 'System.Windows.Forms'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='edktranslation',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='logo-small.ico'
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='edktranslation',
)
