"""add Name for Coze

Revision ID: dd528b95fbb2
Revises: 6bf892b37fb3
Create Date: 2025-11-18 16:12:30.409235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd528b95fbb2'
down_revision: Union[str, Sequence[str], None] = '6bf892b37fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coze', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coze', 'name')
    # ### end Alembic commands ###
